Ran all test suites matching /ShippingAgent.test.js/i.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "After, test("Create", async () => {".

      42 | console.log(`Before, test("Create", async () => {`)
      43 |   	const result = await api.post(entity, boltricsPostData, {xSrForward});
    > 44 | console.log(`After, test("Create", async () => {`)
         |         ^
      45 |     expect(result.body).toMatchObject(boltricsPostData);
      46 |   });
      47 |

      at console.log (../../../../../usr/local/lib/node_modules/jest/node_modules/@jest/console/build/CustomConsole.js:141:10)
      at Object.log (BoltricsApi/tests/ShippingAgent.test.js:44:9)


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "After, test("Delete", async () => {".

      74 | console.log(`Before, test("Delete", async () => {`)
      75 |   	const result = await api.delete(entityEndpoint, {xSrForward})
    > 76 | console.log(`After, test("Delete", async () => {`)
         |         ^
      77 |     expect(result).toMatchObject({status:204 });
      78 |     
      79 | console.log('Before, const result2 = await api.get(entityEndpoint)')

      at console.log (../../../../../usr/local/lib/node_modules/jest/node_modules/@jest/console/build/CustomConsole.js:141:10)
      at Object.log (BoltricsApi/tests/ShippingAgent.test.js:76:9)


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Before, const result2 = await api.get(entityEndpoint)".

      77 |     expect(result).toMatchObject({status:204 });
      78 |     
    > 79 | console.log('Before, const result2 = await api.get(entityEndpoint)')
         |         ^
      80 |     const result2 = await api.get(entityEndpoint)
      81 | console.log('After, const result2 = await api.get(entityEndpoint)')
      82 |     expect(result2.body).toMatchObject(notFoundObject);

      at console.log (../../../../../usr/local/lib/node_modules/jest/node_modules/@jest/console/build/CustomConsole.js:141:10)
      at Object.log (BoltricsApi/tests/ShippingAgent.test.js:79:9)


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "After, const result2 = await api.get(entityEndpoint)".

      79 | console.log('Before, const result2 = await api.get(entityEndpoint)')
      80 |     const result2 = await api.get(entityEndpoint)
    > 81 | console.log('After, const result2 = await api.get(entityEndpoint)')
         |         ^
      82 |     expect(result2.body).toMatchObject(notFoundObject);
      83 |   });
      84 |

      at console.log (../../../../../usr/local/lib/node_modules/jest/node_modules/@jest/console/build/CustomConsole.js:141:10)
      at Object.log (BoltricsApi/tests/ShippingAgent.test.js:81:9)
