// given a non async divide
const divide = (a, b) => {
  if (b === 0) throw new Error('div 0');
  return a/b;
}


// divide usage
console.log(divide(10, 2)); // 5
try {
  console.log(divide(10, 0)); // throw error
} catch (e) {
  console.error(e);
}


/**
 write down an async implementation
 1. using a promise
 2. using a callback
**/





















// hint

// divide promise usage
dividePromise(10, 2).then(
  (result) => console.log(result),
  (error) => console.error(error),
)

// divide callback usage
divideCallback(10, 2, (error, result) => {
  if (error !== undefined) {
    console.error(error);
  } else {
    console.log(result);
  }
});
