Traceback (most recent call last):
  File "main.py", line 57, in wrapper
    job_func(*args, **kwargs)
  File "main.py", line 91, in comment_listener
    database_manager.load_comment(comment, db_conn)
  File "/root/Fallout76MarketplaceKarmaBot/database_manager.py", line 163, in load_comment
    process_command_non_mod_user(comment, db_conn)
  File "/root/Fallout76MarketplaceKarmaBot/database_manager.py", line 139, in process_command_non_mod_user
    flair_functions.increment_karma(comment)
  File "/root/Fallout76MarketplaceKarmaBot/flair_functions.py", line 95, in increment_karma
    assign_karma(p_comment, user_flair)
  File "/root/Fallout76MarketplaceKarmaBot/flair_functions.py", line 48, in assign_karma
    if is_mod_or_courier(p_comment.author):
  File "/root/Fallout76MarketplaceKarmaBot/flair_functions.py", line 23, in is_mod_or_courier
    moderators_list = fallout76marketplace.moderator()
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/models/reddit/subreddit.py", line 2960, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/reddit.py", line 595, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/reddit.py", line 696, in _objectify_request
    self.request(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/reddit.py", line 885, in request
    return self._core.request(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 253, in _request_with_retries
    return self._do_retry(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 253, in _request_with_retries
    return self._do_retry(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 266, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.ServerError: received 502 HTTP response
