TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/alemibot/__main__.py", line 63, in <module>
    app.run()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 80, in run
    run(self.start())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/alemibot/bot.py", line 146, in start
    await super().start()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/pyrogram/client.py", line 591, in load_session
    await self.storage.open()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/pyrogram/storage/file_storage.py", line 61, in open
    self.create()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/alemibot/patches/storage.py", line 39, in create
    with self.lock:
AttributeError: 'DocumentFileStorage' object has no attribute 'lock'
